logging:
  #设置分组
  group:
    ebank: com.chj.controller
    iserver: com.chj
  level:
    #root: debug
    root: info
    #设置某个包的日志级别
    com.chj.controller: info
    ebank: warn

  pattern:
    #console: "%d - %m %n"
    # %d:时间
    # %5p:类型（info,error） 5:占5位格  %clr(){cyan}:颜色 cyan青色
    # --- 无意义
    # %t:线程  []无意义
    # %c:类名  40:占40位格 -:左对齐（默认右对齐） .40:内容截取40位
    # %m:消息
    # %n:换行
    console: "%d %clr(%5p){cyan} --- [%16t] %-40.40c : %m %n"
    #日志文件
    file:
      name: server.log
    #设置日志文件
    logback:
      rollingpolicy:
        #文件最大4KB
        max-file-size: 4KB
        #文件名称 server.2023.03.27.0.log
        # server.日期(指定格式).第几个文件.后缀
        file-name-pattern: server.%d{yyyy-MM-dd}.%i.log

