#应用环境
spring:
  profiles:
    active: test


---
#生产环境
spring:
  profiles: pro
server:
  port: 80

---
#测试环境
spring:
  profiles: test
server:
  port: 81

---
#开发环境
spring:
  profiles: dev
server:
  port: 82